style.css

Vasilis css (test)

---

style.css

Color inherit

---

style.css

Move down the logo in footer

---

style.css

Search Submit sidebar

---

style.css

display: none; as we won't use it.

Remove footer widgets section

---

style.css

Change the Font Family in Headers

---

style.css

Reduce the padding of submit

---

style.css

Change the entry title and entry meta

---

style.css

Change the hover colors in Entry title and Entry Meta

---

style.css

Change the color of body

---

style.css

Change the font-size in Entry Title

---

style.css

Change the background color (default/hover) in submit button

---

style.css

Change the font color in submit button

---

style.css

Change the text color submit button

---

style.css

Change the font family and style of blockquote

---

style.css

Change the fontfamily in entry-content

---

style.css

Increase the box shadow (textwidget)

---

style.css

Remove the text shadow from Search Button

---

style.css

Change the border bottom from solid to dotted (widget sidebar)

---

style.css

Increase / change the color of border-bottom (widget title)

---

style.css

Change the color in border-bottom (widget-title)

---

style.css

Change the hover in widget title

---

style.css

Change the hover color in title of article

---

style.css

Change the hover color in navigation menu

---

style.css

Return to default

---

style.css

Reduce the font-size (title of organizers)

---

style.css

Increase the size of social media and margin-right.

Social Media icons

---

style.css

Change the hover (footer)

---

style.css

Override the color (facebook-sidebar)

---

style.css

Customize social media

---

style.css

Default social colors

---

style.css

Hover colors (social Media)

---

style.css

Change the color instagram

---

style.css

transition social

---

style.css

Add bottom navigation (mobile view)

---

style.css

Updated Version. (.entry-content h2, .comment-content h2)

Reduce the font-size of title (organizers)

---

style.css

Align in left

---

style.css

Change the a href (default/hover)
